
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 08 14:23:26 BRT 2022
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SIMBOLO_ATRIBUICAO = 22;
  public static final int COMENTARIO_BLOCO_SEM_ABRIR = 44;
  public static final int RESERVADO_BEGIN = 5;
  public static final int OPERACAO_NOT = 35;
  public static final int OPERACAO_AND = 34;
  public static final int RESERVADO_TRUE = 12;
  public static final int DOIS_PONTOS = 17;
  public static final int COMENTARIO_LINHA = 41;
  public static final int VIRGULA = 18;
  public static final int PONTO = 19;
  public static final int IDENTIFICADOR = 39;
  public static final int OPERACAO_DIV = 31;
  public static final int IDENTIFICADOR_MUITO_GRANDE = 40;
  public static final int OPERACAO_IGUAL = 28;
  public static final int RESERVADO_END = 6;
  public static final int RESERVADO_IF = 7;
  public static final int RESERVADO_ELSE = 9;
  public static final int RESERVADO_VAR = 3;
  public static final int EOF = 0;
  public static final int COMENTARIO_BLOCO_SEM_FECHAR = 43;
  public static final int PONTO_VIRGULA = 16;
  public static final int ABRE_PARENTESES = 20;
  public static final int RESERVADO_WHILE = 10;
  public static final int RESERVADO_THEN = 8;
  public static final int error = 1;
  public static final int NUMERO_REAL_FORMATO_RUIM = 36;
  public static final int OPERACAO_MAIOR = 24;
  public static final int NUMERO_REAL = 38;
  public static final int OPERACAO_MENOR_IGUAL = 25;
  public static final int RESERVADO_PROCEDURE = 4;
  public static final int OPERACAO_MULT = 32;
  public static final int OPERACAO_MAIOR_IGUAL = 26;
  public static final int COMENTARIO_BLOCO = 42;
  public static final int OPERACAO_MENOR = 23;
  public static final int RESERVADO_INTEGER = 14;
  public static final int OPERACAO_SOMA = 29;
  public static final int OPERACAO_OR = 33;
  public static final int RESERVADO_FALSE = 13;
  public static final int FECHA_PARENTESES = 21;
  public static final int CHAR_INVALIDO = 45;
  public static final int OPERACAO_SUB = 30;
  public static final int RESERVADO_DO = 11;
  public static final int OPERACAO_DIFERENTE = 27;
  public static final int RESERVADO_BOOLEAN = 15;
  public static final int NUMERO_INTEIRO = 37;
  public static final int RESERVADO_PROGRAM = 2;
}

